- name: Deploy
  hosts: zalo_mini_app_theme_2
  tasks:
    - name: Git Pull
      ansible.builtin.shell: cd zalo_mini_app_theme_2 && git pull origin master

    - name: NPM Install
      command: bash -lc "cd zalo_mini_app_theme_2 && sudo npm install"

- name: Restart
  hosts: zalo_mini_app_theme_2
  serial: 1
  tasks:
    - name: Restart
      command: bash -lc "pm2 restart theme-2 --update-env"
